const mongoose = require('mongoose');

const EmploymentSchema = new mongoose.Schema({
  providerID: String,
  stateOrTerritory: String,
  LGA: String,
  surname: String,
  firstName: String,
  dateOfBirth: Date,
  gender: String,
  NDISParticipantNumber: String,
  primaryDisability: String,
  employmentServiceStartDate: Date,
  reportingPeriod_periodStart: Date,
  reportingPeriod_periodEnd: Date,
  supportProvided_Assessment_hoursSpent: Number,
  supportProvided_Planning_and_reviewing_progress_hoursSpent: Number,
  supportProvided_Exploring_employment_options_hoursSpent: Number,
  supportProvided_Engagement_with_family_hoursSpent: Number,
  supportProvided_Engagement_with_professionals_hoursSpent: Number,
  supportProvided_Building_social_skills_progressTowardsMilestone: String,
  supportProvided_Building_social_skills_hoursSpent: Number,
  supportProvided_Travel_training_progressTowardsMilestone: String,
  supportProvided_Travel_training_hoursSpent: Number,
  supportProvided_Work_skill_training_progressTowardsMilestone: String,
  supportProvided_Work_skill_training_hoursSpent: Number,
  supportProvided_Employer_engagement_progressTowardsMilestone: String,
  supportProvided_Employer_engagement_hoursSpent: Number,
  supportProvided_Work_experience_support_progressTowardsMilestone: String,
  supportProvided_Work_experience_support_hoursSpent: Number,
  supportProvided_On_the_job_support_progressTowardsMilestone: String,
  supportProvided_On_the_job_support_hoursSpent: Number,
  supportProvided_Other_activity_description: String,
  supportProvided_Other_progressAchieved: String,
  supportProvided_Other_hoursSpent: Number,
  supportProvided_Additional_notes: String,
  totalSupportHours_totalHours: Number,
  totalSupportHours_oneToOnePercentage: Number,
  totalSupportHours_groupBasedPercentage: Number,
  totalSupportHours_distanceOnlinePercentage: Number,
  totalSupportHours_totalPercentage: Number,
  finalOutcome_continueSupportNextPeriod: String,
  finalOutcome_outcomeAtExit: String,
  finalOutcome_exitDate: Date,
  finalOutcome_exitNotes: String,
  employmentDetails_status: String,
  employmentDetails_industry: String,
  employmentDetails_employerName: String,
  employmentDetails_averageWeeklyHours: Number,
  employmentDetails_usingNDISSupportsInEmployment: String,
  employmentDetails_supportedWages: String,
  employmentDetails_startDate: Date,
  employmentDetails_employmentNotes: String,
});

module.exports = mongoose.model('Employment', EmploymentSchema);

